services:
  postgres:
    image: postgres:16-alpine
    container_name: incident_app_pg
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: incident
      POSTGRES_PASSWORD: incident
      POSTGRES_DB: incident_app
    volumes:
      - incident_app_pg:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U incident -d incident_app']
      interval: 2s
      timeout: 3s
      retries: 10

volumes:
  incident_app_pg:
